name: Deploy Python Azure Function to Linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies to build output folder
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --target=".python_packages/lib/site-packages" -r requirements.txt

      - name: Zip the function app
        run: |
          zip -r functionapp.zip .

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_FUNCTION_CREDENTIALS }}

      - name: Deploy via zip
        run: |
          az functionapp deployment source config-zip \
            --name FuncAgentMiddleware-dev-v2 \
            --resource-group DefaultResourceGroup-EUS \
            --src functionapp.zip
